jobs:
    include:
        - language: java
          jdk: openjdk8
          sudo: true
          script:
              - ./gradlew assemble
              - ./gradlew check
              - ./gradlew buildOfficial

        - language: node_js
          node_js: 10
          script:
              - cd tnoodle-ui
              - npm install
              - npm test -- --coverage
          after_script:
              - COVERALLS_REPO_TOKEN=$coveralls_repo_token npm run coveralls
